DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS cliant;
DROP TABLE IF EXISTS family;
DROP TABLE IF EXISTS apidata;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

